### ISSUE TITLE
Add NodeSelector, Tolerations, and Affinity for Each Odigos Component

### ISSUE THREAD

**Issue by clavinjune** [keyval-dev/odigos-charts#23]
This is related to https://github.com/keyval-dev/odigos/issues/927, we want to be able to manage on which node the Odigos component can/can't be deployed

cc @blumamir @esara

**Comment by clavinjune** [comment]
please help assign this to me :bow:

**Comment by esara** [comment]
happy to help - the current chart hardcodes the nodeselector as
```
      nodeSelector:
        kubernetes.io/os: linux
```
https://github.com/keyval-dev/odigos-charts/blob/master/charts/odigos/templates/odiglet/daemonset.yaml

we can keep this as the default - but add options to customize selectors, tolerations and affinity..
especially for the daemonset - but also if you wish for other components

would you suggest each component to be configurable individually? 

ps: I think there was a previous attempt at this https://github.com/keyval-dev/odigos-charts/issues/15 from @tospe

**Comment by clavinjune** [comment]
sorry @esara, just read your comment, yes I already add `kubernetes.io/os: linux` as the default, the configuration will be separated for each component, and yes, I guess #15 is the subset of this issue
