### ISSUE TITLE
nodeSelector not present in template files

### ISSUE THREAD

**Issue by davehardyuk** [keyval-dev/odigos-charts#5]
Hi,

I'm running a cluster which has both Linux and Windows nodes. I'm finding that when deploying Odigos, the pods get distributed over both platforms and only the linux ones start running.

Are you able to add 

```
nodeSelector:
    kubernetes.io/os: linux
```

To the deployment template files to force the pods to go onto Linux OS nodes? 

Many thanks

**Comment by edeNFed** [comment]
Thank you for reporting. Just merged a fix
